// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: rpc_greet_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *GreetUserRequest) Reset() {
	*x = GreetUserRequest{}
	mi := &file_rpc_greet_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetUserRequest) ProtoMessage() {}

func (x *GreetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_greet_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetUserRequest.ProtoReflect.Descriptor instead.
func (*GreetUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_greet_user_proto_rawDescGZIP(), []int{0}
}

func (x *GreetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GreetUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type GreetUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GreetUserResponse) Reset() {
	*x = GreetUserResponse{}
	mi := &file_rpc_greet_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetUserResponse) ProtoMessage() {}

func (x *GreetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_greet_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetUserResponse.ProtoReflect.Descriptor instead.
func (*GreetUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_greet_user_proto_rawDescGZIP(), []int{1}
}

func (x *GreetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GreetUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_greet_user_proto protoreflect.FileDescriptor

var file_rpc_greet_user_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x10, 0x47, 0x72, 0x65, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65,
	0x22, 0x4b, 0x0a, 0x11, 0x47, 0x72, 0x65, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x20, 0x5a,
	0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x6f, 0x6e,
	0x67, 0x6c, 0x69, 0x74, 0x2f, 0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x65, 0x77, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_greet_user_proto_rawDescOnce sync.Once
	file_rpc_greet_user_proto_rawDescData = file_rpc_greet_user_proto_rawDesc
)

func file_rpc_greet_user_proto_rawDescGZIP() []byte {
	file_rpc_greet_user_proto_rawDescOnce.Do(func() {
		file_rpc_greet_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_greet_user_proto_rawDescData)
	})
	return file_rpc_greet_user_proto_rawDescData
}

var file_rpc_greet_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_greet_user_proto_goTypes = []any{
	(*GreetUserRequest)(nil),  // 0: pb.GreetUserRequest
	(*GreetUserResponse)(nil), // 1: pb.GreetUserResponse
	(*User)(nil),              // 2: pb.User
}
var file_rpc_greet_user_proto_depIdxs = []int32{
	2, // 0: pb.GreetUserResponse.user:type_name -> pb.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_greet_user_proto_init() }
func file_rpc_greet_user_proto_init() {
	if File_rpc_greet_user_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_greet_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_greet_user_proto_goTypes,
		DependencyIndexes: file_rpc_greet_user_proto_depIdxs,
		MessageInfos:      file_rpc_greet_user_proto_msgTypes,
	}.Build()
	File_rpc_greet_user_proto = out.File
	file_rpc_greet_user_proto_rawDesc = nil
	file_rpc_greet_user_proto_goTypes = nil
	file_rpc_greet_user_proto_depIdxs = nil
}
